'use strict';
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const reduce = matchMedia('(prefers-reduced-motion: reduce)');
const menu = $('.menu-toggle');
menu.addEventListener('click', () => { const open = menu.getAttribute('aria-expanded') !== 'true'; menu.setAttribute('aria-expanded', String(open)); menu.setAttribute('aria-label', open ? 'Close navigation' : 'Open navigation'); $('#navigation').classList.toggle('open',open); });
$$('#navigation a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');$('#navigation').classList.remove('open');}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#navigation').classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');}});
$$('.service').forEach(d=>d.addEventListener('toggle',()=>{if(!d.open)return;$$('.service').filter(x=>x!==d).forEach(x=>x.open=false);$('#treatment-photo').src='assets/'+d.dataset.image;$('#treatment-photo').alt=d.dataset.alt;}));
function goBooking(service){$('#service-select').value=service;$('#booking').scrollIntoView({behavior:reduce.matches?'instant':'smooth'});}
$$('.select-service').forEach(b=>b.addEventListener('click',()=>goBooking(b.dataset.service)));
let selectedLook=null;
const lookDialog=$('#look-dialog');lookDialog.setAttribute('aria-labelledby','look-title');
function openDialog(d){d.showModal();document.body.classList.add('modal-open');}
$$('dialog').forEach(d=>{d.addEventListener('close',()=>document.body.classList.remove('modal-open'));$('.dialog-close',d).addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
$$('.look').forEach(b=>b.addEventListener('click',()=>{selectedLook={name:b.dataset.look,service:b.dataset.service,src:$('img',b).getAttribute('src'),alt:$('img',b).alt};$('#look-title').textContent=selectedLook.name;$('#dialog-image').src=selectedLook.src;$('#dialog-image').alt=selectedLook.alt;openDialog(lookDialog);}));
let bookingLook=null;
$('#use-look').addEventListener('click',()=>{bookingLook={...selectedLook};const s=$('#selected-look');$('img',s).src=bookingLook.src;$('img',s).alt=bookingLook.alt;$('strong',s).textContent=bookingLook.name;s.hidden=false;lookDialog.close();goBooking(bookingLook.service);});
$('#clear-look').addEventListener('click',()=>{bookingLook=null;$('#selected-look').hidden=true;});
const gallery=$('#gallery');
function updateArrows(){const end=gallery.scrollWidth-gallery.clientWidth;$('#gallery-prev').disabled=gallery.scrollLeft<5;$('#gallery-next').disabled=gallery.scrollLeft>=end-5;}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});let count=0;$$('.look').forEach(x=>{x.hidden=b.dataset.filter!=='all'&&x.dataset.category!==b.dataset.filter;if(!x.hidden)count++;});$('#gallery-count').textContent=count+' looks';gallery.scrollLeft=0;updateArrows();}));
$('#gallery-prev').addEventListener('click',()=>gallery.scrollBy({left:-gallery.clientWidth*.78,behavior:reduce.matches?'instant':'smooth'}));$('#gallery-next').addEventListener('click',()=>gallery.scrollBy({left:gallery.clientWidth*.78,behavior:reduce.matches?'instant':'smooth'}));gallery.addEventListener('scroll',updateArrows,{passive:true});window.addEventListener('resize',updateArrows);updateArrows();
const date=$('#preferred-date');const today=new Date();date.min=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');
let enquiry='';$('#booking-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const preferred=f.get('date');if(preferred&&preferred<date.min){date.setCustomValidity('Please choose today or a future date.');date.reportValidity();return;}date.setCustomValidity('');enquiry=`Hello Dee,\n\nI'd like to enquire about an appointment.\n\nName: ${f.get('name').trim()}\nEmail: ${f.get('email').trim()}\nTreatment: ${f.get('service')}${preferred?'\nPreferred date: '+preferred:''}${bookingLook?'\nLookbook inspiration: '+bookingLook.name:''}${f.get('message').trim()?'\n\n'+f.get('message').trim():''}\n\nPlease let me know your pricing and availability.\nThank you!`;
$('#enquiry-preview').textContent=enquiry;$('#send-email').href='mailto:hello@divinebeautybydee.com?subject='+encodeURIComponent('Appointment enquiry · '+f.get('service'))+'&body='+encodeURIComponent(enquiry);const result=$('#enquiry-result');result.hidden=false;result.focus({preventScroll:true});result.scrollIntoView({behavior:reduce.matches?'instant':'smooth',block:'center'});});date.addEventListener('input',()=>date.setCustomValidity(''));
$('#copy-enquiry').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(enquiry);$('#copy-status').textContent='Message copied. Paste it into your email to Dee.';}catch{$('#copy-status').textContent='Select and copy the message above, or choose Open email app.';}});
const info=$('#info-dialog');info.setAttribute('aria-labelledby','info-title');
$('#privacy-open').addEventListener('click',()=>{$('#info-title').textContent='Your privacy';$('#info-content').innerHTML='<p>The enquiry form prepares a message in your browser. Your details are not submitted to a booking system or saved by this page.</p><p>When you choose “Open email app”, your email app opens a draft addressed to the studio. You decide whether to send it. The studio receives your details only when you send that email.</p><p>This site does not use advertising or analytics cookies. Fonts are requested from Google Fonts. Your hosting provider may process ordinary technical request information.</p><p>For questions about an enquiry you have sent, contact <a href="mailto:hello@divinebeautybydee.com">hello@divinebeautybydee.com</a>.</p>';openDialog(info);});
$('#credits-open').addEventListener('click',()=>{$('#info-title').textContent='Behind the imagery';$('#info-content').innerHTML='<p>Brand photography and logo are carried over from the client’s original Divine Beauty & Nails By Dee website.</p><p>Editorial film: <a href="https://www.pexels.com/video/close-up-of-elegant-hand-with-red-nails-35049544/" target="_blank" rel="noopener">Salim Da on Pexels</a> and <a href="https://www.pexels.com/video/close-up-on-manicure-10609138/" target="_blank" rel="noopener">cottonbro studio on Pexels</a>. Used under the <a href="https://www.pexels.com/license/" target="_blank" rel="noopener">Pexels licence</a>.</p><p>The film is beauty inspiration and does not depict a treatment performed by Dee.</p>';openDialog(info);});
const videos=$$('video[data-video]');
function syncVideo(v){const b=$(`[data-target="${v.id}"]`);if(!b)return;$('.control-label',b).textContent=v.paused?'Play film':'Pause film';$('span',b).textContent=v.paused?'▶':'Ⅱ';b.setAttribute('aria-label',(v.paused?'Play':'Pause')+' beauty film');}
function loadVideo(v){if(!v.getAttribute('src')){v.src=v.dataset.video;v.load();}}
const videoObserver=new IntersectionObserver(entries=>entries.forEach(({target:v,isIntersecting})=>{v.dataset.visible=String(isIntersecting);if(isIntersecting&&!reduce.matches&&v.dataset.userPaused!=='true'&&!navigator.connection?.saveData){loadVideo(v);v.play().catch(()=>syncVideo(v));}else v.pause();}),{threshold:.15});
videos.forEach(v=>{videoObserver.observe(v);['play','pause'].forEach(t=>v.addEventListener(t,()=>syncVideo(v)));v.addEventListener('error',()=>{const b=$(`[data-target="${v.id}"]`);$('.control-label',b).textContent='Film unavailable';b.disabled=true;});});
$$('.film-control').forEach(b=>b.addEventListener('click',()=>{const v=document.getElementById(b.dataset.target);if(v.paused){v.dataset.userPaused='false';loadVideo(v);v.play().catch(()=>syncVideo(v));}else{v.dataset.userPaused='true';v.pause();}}));
document.addEventListener('visibilitychange',()=>videos.forEach(v=>{if(document.hidden)v.pause();else if(v.dataset.visible==='true'&&!reduce.matches&&v.dataset.userPaused!=='true'&&!navigator.connection?.saveData)v.play().catch(()=>{});}));
reduce.addEventListener('change',()=>{if(reduce.matches){videos.forEach(v=>v.pause());$('.hero-photo img').style.transform='';$('.hero-inset').style.transform='';}});
const hero=$('.hero'),heroPhoto=$('.hero-photo img'),heroInset=$('.hero-inset');let pending=false;
function depth(){pending=false;if(reduce.matches||innerWidth<801)return;const r=hero.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;const p=Math.max(0,Math.min(1,-r.top/r.height));heroPhoto.style.transform=`translateY(${p*65}px) scale(${1+p*.035})`;heroInset.style.transform=`translateY(${-p*45}px) rotate(${4-p*3}deg)`;}
addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(depth);}},{passive:true});
if(matchMedia('(hover:hover) and (pointer:fine)').matches){hero.addEventListener('pointermove',e=>{if(reduce.matches||innerWidth<801)return;const x=(e.clientX/innerWidth-.5)*7;heroInset.style.translate=`${x}px 0`;});hero.addEventListener('pointerleave',()=>heroInset.style.translate='0 0');}
if(window.ScrollCraft)window.ScrollCraft.mount(document.querySelector('main'));
